name: Ulticraft
main: com.ulticraft.Ulticraft
version: 3.1.27.1337
depend: [Vault]
commands:
  gem:
    aliases: [gems]
  perk:
    aliases: [perks]
  spell:
    aliases: [spells]
  mana:
    aliases: [magic]
  ulticraft:
    aliases: [u]